project:
  type: website
website:
  title: "Website Creation: A Quarto Tutorial"
  navbar: #or sidebar
    style: "floating"
    left: # contents with sidebar
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Resume & CV
        menu:
        - href: Resume.pdf
          text: Resume
        - href: CV.pdf
          text: CV
      - href: projects.qmd
        text: Projects
      - href: Presentation.qmd
        text: Presentation
      - icon: github
        href: https://github.com/bsgallih12
      - icon: twitter
        href: https://twitter.com/Brier_Gallihugh
      - icon: envelope
        href: mailto:bg464219@ohio.edu
format:
  html:
    theme: darkly
    toc: true
    css: styles.css



