project:
  type: website
website:
  title: "Academic and Personal Website Creation: A Quarto Tutorial"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      # - text: Resume & CV
      #   menu:
      #   - href: Resume.pdf
      #     text: Resume
      #   - href: CV.pdf
      #     text: CV
      # - href: projects.qmd
      #   text: Projects
      # - icon: github
      #   href: https://github.com/bsgallih12
      # - icon: twitter
      #   href: https://twitter.com/Brier_Gallihugh
format:
  html:
    theme: flatly
      # light: flatly
      # dark: darkly
    css: styles.css
    toc: true

